### ISSUE TITLE
CC2531ZNP-Test.rar configuration

### ISSUE THREAD

**Issue by splitice** [zigbeer/documents#1]
Hey mate,

Would you be able to share the required configuration to compile the binary?

**Comment by jackchased** [comment]
Hi @splitice ,

I need to find out the compile options for configurations. Could you please provide me your email address?

**Comment by splitice** [comment]
@jackchased certainly mheard@x4b.net

**Comment by jackchased** [comment]
Hello @splitice, may we close this issue?

**Comment by splitice** [comment]
Yes thanks for sending that via email. We were able to replicate your build.

FYI, I don't believe the Pre-Processor defines would be covered by any Licence or Restriction by TI. They would be a good addition to this repository.

Disclaimer: Not a Lawyer.

**Comment by itsmepetrov** [comment]
@jackchased @splitice could you please share them for me too? petrov.aap@gmail.com
